### ISSUE TITLE
Update site review app reactivity

### ISSUE THREAD

**Issue by jakevl** [ut-ir-tools/irTools#14]

**Comment by jakevl** [comment]
Updates made. Ready for testing.

**Comment by edhinman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test site review app reactivity.](https://trello.com/c/IJTrymLL/46-test-site-review-app-reactivity)

**Comment by edhinman** [comment]
Re-ran site validation app. 
- Accepted and merged sites. (success)
- Accepted sites for nonsensical reasons. (success, needs a later check?)
- Rejected multiple sites within close proximity. (success)
- Refreshed map after saving changes to ensure points are no longer flagged for REVIEW. (success)
- Toggled between site and AU polygon layers. (success)
** did not toggle between ACCEPT, REVIEW, REJECT data.
