### ISSUE TITLE
dataPrep()

### ISSUE THREAD

**Issue by jakevl** [ut-ir-tools/irTools#6]
Need to assign criteria & generate table first:
- [x] Perform unit conversions 
- [ ] Multiple records per day?
- [x] Activity types (check that native == target)
- [x] Fraction types (check that native == target)

Final pre-assessment data prep steps:
- [x] Dissolved > total fraction
- [ ] River/streams samples w/ associated depths (reject depth >= 4 m)
- [ ] Flow (potential visual review?)

Potential flags:
- [ ] Value based flags/rejections (i.e. CRAZY VALUES!!!!)
- [ ] Sample vs. lab dates/times? Holding times?
- [ ] Estimated vs. calculated

 

Any others?

**Comment by jakevl** [comment]
See dataPrep() function outline in data-prep branch.

**Comment by jakevl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Final data cleanup](https://trello.com/c/A3Hs2wMT/24-final-data-cleanup)

**Comment by edhinman** [comment]
Jake, do we need to add a case-insensitive grepl function for isolating dissolved and total records (e.g. someone types in DISSOLVED v. dissolved), or does WQP constrain this part of the data entry process?
